// Optional touch regression using Chromium's native touch input, not mouse events.
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright-core');
const root = fileURLToPath(new URL('../', import.meta.url));
const artifacts = path.join(root, 'dist/browser-artifacts');
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
try {
  let html = await readFile(path.join(root, 'dist/iron-front-demo.html'), 'utf8');
  html = html.replace('</script>', '\nwindow.__testingGame=()=>game;window.__testingInput=()=>({selected:[...selected],camera:{...camera},placement,attackMode,abilityMode,paused,touches:touchPointers.size});\n</script>');
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 3 });
  const page = await context.newPage(), errors = []; let requests = 0;
  page.on('pageerror', e => errors.push(e.message)); page.on('request', () => requests++);
  const cdp = await context.newCDPSession(page);
  const input = () => page.evaluate(() => __testingInput());
  const send = (type, points = []) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([id, x, y]) => ({ id, x, y, radiusX: 5, radiusY: 5, force: 1 })) });
  const worldScreen = async (x, y) => { const { camera } = await input(), b = await page.locator('#battle').boundingBox(); return { x: b.x + x - camera.x, y: b.y + y - camera.y }; };
  const tapWorld = async (x, y) => { const p = await worldScreen(x, y); await page.touchscreen.tap(p.x, p.y); };
  await page.setContent(html);
  await page.locator('#deploy').tap();
  await page.waitForTimeout(250);
  assert.equal(await page.locator('.touch-controls').isVisible(), true);
  assert.equal(await page.locator('#command-panel').isVisible(), false);
  assert.equal((await page.locator('#battle').boundingBox()).width, 390);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  for (const id of ['mobile-select', 'mobile-attack', 'mobile-stop', 'mobile-home', 'mobile-command']) assert.ok((await page.locator(`#${id}`).boundingBox()).height >= 44);
  const arrange = () => page.evaluate(() => {
    const g = __testingGame(), c = __testingInput().camera;
    g.credits = 20000; g.waveAt = Infinity;
    const rifles = g.entities.filter(e => e.team === 'player' && e.type === 'rifle');
    for (const e of g.entities.filter(e => e.team === 'player' && !e.building && e.type !== 'harvester')) { e.order = null; e.path = []; e.x = c.x + 290; e.y = c.y + 320; e.cooldown = 1000; }
    rifles[0].x = c.x + 105; rifles[0].y = c.y + 175;
    rifles[1].x = c.x + 175; rifles[1].y = c.y + 225;
    return rifles.slice(0, 2).map(e => ({ id: e.id, x: e.x, y: e.y }));
  });
  let [hero, buddy] = await arrange();
  await tapWorld(hero.x, hero.y);
  assert.deepEqual((await input()).selected, [hero.id]);
  const c = (await input()).camera, destination = { x: c.x + 265, y: c.y + 100 };
  await tapWorld(destination.x, destination.y);
  assert.deepEqual((await input()).selected, [hero.id]);
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order?.x, hero.id), destination.x);
  await page.locator('#mobile-stop').tap();
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order, hero.id), null);
  console.log('PASS touch: select, move while retaining selection, stop, full-width battlefield and 44px controls.');

  const beforePan = await input(), b = await page.locator('#battle').boundingBox();
  await send('touchStart', [[0, 100, b.y + 350], [1, 230, b.y + 350]]);
  await send('touchMove', [[0, 40, b.y + 310], [1, 170, b.y + 310]]);
  await page.waitForTimeout(80);
  const afterPan = await input();
  assert.ok(Math.abs(afterPan.camera.x - beforePan.camera.x - 60) < 1);
  assert.ok(Math.abs(afterPan.camera.y - beforePan.camera.y - 40) < 1);
  await send('touchEnd', [[0, 40, b.y + 310]]);
  await send('touchMove', [[0, 80, b.y + 350]]);
  await send('touchEnd');
  await page.waitForTimeout(600);
  assert.deepEqual((await input()).camera, afterPan.camera);
  assert.deepEqual((await input()).selected, [hero.id]);
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order, hero.id), null);
  assert.equal((await input()).touches, 0);
  assert.equal(await page.evaluate(() => scrollY), 0);
  console.log('PASS touch: two-finger pan, no residual command after lifting either finger, no edge-scroll drift.');

  await page.locator('#mobile-home').tap(); await page.locator('#mobile-cancel').tap();
  [hero, buddy] = await arrange();
  const start = await worldScreen(hero.x - 25, hero.y - 25), end = await worldScreen(buddy.x + 25, buddy.y + 25);
  await send('touchStart', [[0, start.x, start.y]]);
  await send('touchMove', [[0, start.x + 25, start.y + 25]]);
  await send('touchMove', [[0, end.x, end.y]]);
  await send('touchEnd');
  assert.deepEqual(new Set((await input()).selected), new Set([hero.id, buddy.id]));
  await page.locator('#mobile-cancel').tap(); await tapWorld(hero.x, hero.y);
  const enemy = await page.evaluate(() => { const c = __testingInput().camera; return __testingGame().add('rifle', 'enemy', c.x + 265, c.y + 200, { cooldown: 1000 }); });
  const enemyPoint = await worldScreen(enemy.x, enemy.y);
  await send('touchStart', [[0, enemyPoint.x, enemyPoint.y]]); await page.waitForTimeout(550); await send('touchEnd');
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order?.targetId, hero.id), enemy.id);
  await page.locator('#mobile-stop').tap();
  await page.locator('#mobile-attack').tap(); await tapWorld(destination.x, destination.y);
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order?.attackMove, hero.id), true);
  await page.locator('#mobile-stop').tap();
  await send('touchStart', [[0, enemyPoint.x, enemyPoint.y]]); await send('touchCancel'); await page.waitForTimeout(550);
  assert.equal(await page.evaluate(id => __testingGame().entities.find(e => e.id === id).order, hero.id), null);
  assert.equal((await input()).touches, 0);
  await page.locator('#pause').tap(); const selection = (await input()).selected;
  await tapWorld(destination.x, destination.y); assert.deepEqual((await input()).selected, selection);
  await page.locator('#pause').tap();
  console.log('PASS touch: box selection, long-press attack, attack-move, cancelled gesture and pause.');

  await page.locator('#mobile-command').tap();
  assert.equal(await page.locator('#command-panel').isVisible(), true);
  await page.locator('[data-type="power"]').tap();
  assert.equal(await page.locator('#command-panel').isVisible(), false);
  assert.equal((await input()).placement, 'power');
  // Two fingers while placing must move the map without queuing a building.
  const queueBefore = await page.evaluate(() => __testingGame().queue.length);
  await send('touchStart', [[0, 100, b.y + 350], [1, 230, b.y + 350]]);
  await send('touchMove', [[0, 80, b.y + 330], [1, 210, b.y + 330]]); await send('touchEnd');
  assert.equal(await page.evaluate(() => __testingGame().queue.length), queueBefore);
  await page.locator('#mobile-home').tap();
  const spot = await page.evaluate(() => { const g = __testingGame(), c = __testingInput().camera; for (let y = c.y + 100; y < c.y + 550; y += 20) for (let x = c.x + 60; x < c.x + 330; x += 20) if (g.canBuild('power', x, y)) return { x, y }; });
  assert.ok(spot); await tapWorld(spot.x, spot.y);
  assert.equal((await input()).placement, null);
  assert.equal(await page.evaluate(() => __testingGame().queue.some(q => q.type === 'power')), true);
  await page.evaluate(() => { for (let i = 0; i < 130; i++) __testingGame().update(.1); });
  await page.locator('#mobile-command').tap(); await page.locator('#unit-tab').tap(); await page.locator('[data-type="medic"]').tap();
  assert.equal(await page.evaluate(() => __testingGame().queue.some(q => q.type === 'medic')), true);
  await page.screenshot({ path: path.join(artifacts, 'touch-production.png') });
  // Verify the menu scrolls with real touch input while the page stays fixed.
  const menu = await page.locator('#command-panel').boundingBox();
  await send('touchStart', [[0, 200, menu.y + menu.height - 60]]);
  await send('touchMove', [[0, 200, menu.y + 200]]); await send('touchMove', [[0, 200, menu.y + 90]]); await send('touchEnd');
  await page.waitForTimeout(250);
  assert.ok(await page.locator('#command-panel').evaluate(e => e.scrollTop) > 0);
  assert.equal(await page.evaluate(() => scrollY), 0);
  await page.locator('#close-command').tap();
  await page.locator('#mobile-command').tap(); await page.locator('#ability').tap();
  assert.equal(await page.locator('#command-panel').isVisible(), false);
  assert.equal((await input()).abilityMode, true);
  await page.locator('#mobile-cancel').tap(); assert.equal((await input()).abilityMode, false);
  await page.locator('#mobile-command').tap(); await page.locator('#ability').tap(); await tapWorld(410, 1020);
  assert.ok(await page.evaluate(() => __testingGame().abilityReadyAt > __testingGame().time));
  await page.screenshot({ path: path.join(artifacts, 'touch-portrait.png') });
  console.log('PASS touch: drawer, placement, pan without placement, production, native menu scrolling, support skill and cancel.');

  const beforeRotation = (await input()).camera;
  await page.setViewportSize({ width: 844, height: 390 }); await page.waitForTimeout(250);
  assert.ok(Math.abs((await input()).camera.y - beforeRotation.y - 227) < 1, 'rotation preserves the vertical center of the battlefield');
  assert.equal((await page.locator('#battle').boundingBox()).width, 844);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('#mobile-command').tap();
  const landscapeMenu = await page.locator('#command-panel').boundingBox(); assert.equal(landscapeMenu.width, 310); assert.ok(landscapeMenu.y + landscapeMenu.height <= 391);
  await page.locator('#close-command').tap(); await page.locator('#mobile-select').tap(); assert.ok((await input()).selected.length > 1);
  await page.screenshot({ path: path.join(artifacts, 'touch-landscape.png') });
  await page.setViewportSize({ width: 320, height: 640 }); await page.waitForTimeout(250);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('#mobile-command').tap(); await page.locator('#new-game').tap(); await page.locator('#resume-game').tap();
  assert.equal(await page.locator('#command-panel').isVisible(), false);
  assert.deepEqual(errors, []); assert.equal(requests, 0);
  console.log('PASS touch: portrait/landscape rotation, 320px screen, all-units selection, country menu, no JavaScript errors or external requests.');
} finally { await browser.close(); }
